### ISSUE TITLE
67JT

### ISSUE THREAD

**Issue by kaurharmandeep** [ShabadOS/database#674] opened 2019-03-29 01:08 UTC
| Key | Value |
| --- | --- |
| ID | 67JT |
| Source | Vaaran Bhai Gurdas Ji |
| Page | 31 |
| Line | mUriq iekw nwau duie; Drm rwie jm dyiK sirTw [ |
| Correction | Drm rwie ≠ Drmrwie |

PROOF (EDITION)

Image:
<img width="379" alt="Vaaran114" src="https://user-images.githubusercontent.com/31778082/55202409-ad41d980-519d-11e9-8b14-c92cb3f26a4d.PNG">

**Comment by bhajneet** [comment] 2019-05-12 16:06
Duplicate of #672

**Closed by bhajneet** 2019-05-12 16:06 UTC
