### ISSUE TITLE
67JT

### ISSUE THREAD

**Issue by kaurharmandeep** [ShabadOS/database#673] opened 2019-03-29 01:07 UTC
| Key | Value |
| --- | --- |
| ID | 67JT |
| Source | Vaaran Bhai Gurdas Ji |
| Page | 31 |
| Line | mUriq iekw nwau duie; Drm rwie jm dyiK sirTw [ |
| Correction | Drm rwie ≠ Drmrwie |

PROOF (EDITION)

Image:
<img width="415" alt="Vaaran113" src="https://user-images.githubusercontent.com/31778082/55202359-78ce1d80-519d-11e9-94ff-2480587fc660.PNG">

**Comment by bhajneet** [comment] 2019-05-12 16:06
Duplicate of #671

**Closed by bhajneet** 2019-05-12 16:06 UTC
