### ISSUE TITLE
pad chhed not same as proof

### ISSUE THREAD

**Issue by HarminderSingh** [ShabadOS/database#274] opened 2019-02-11 19:40 UTC
20rgs dis is my first issue only so please give me maafi. i notice pad chhed not same on many sabads in proofs and in data. i can give examples, but there are too many.

**Comment by Sarabveer** [comment] 2019-02-11 20:46
Duplicate of #275

**Closed by Sarabveer** 2019-02-11 20:46 UTC
Labels: correction

**Comment by Sarabveer** [comment] 2019-02-11 20:51
Related to issue #95

**Comment by bhajneet** [comment] 2019-02-11 21:10
Veer ji,

Thank you for submitting the issues. This issue was closed for being too generic.

The larrivaar SGGS ji has been triple-checked at this point and should be 100% accurate. The example, you have provided, to use Sttm db would actually be worse for larrivaar. We have checked their DB multiple times over the past year and for SGGS ji there are still many mistakes in their DB that are not pad chhed related.

Pad chhed itself is a tricky matter because even SGPC has differences between themselves. However, we are trying our best to improve those as well. As a solution we are going to implement an alternate pad chhed field in the db, so it can be easier to see on which lines that even SGPC also differs.

In the end, technically all was written as larrivaar, so our first goal is to make sure that the letters themselves are correct. We are equally working on improving the pad chhed.

Currently, we are actively working on Sri Dasam Granth and Bhai Gurdaas Ji Vaaran. Perhaps you are finding many mistakes and examples in other banis such as these?

If you can provide more examples like you've done in #275 that will be helpful. If you'd rather we speak over chat to explain better, we are more than willing to discuss the broader issue with you on slack or over whatsapp.

Again thank you for your concerns, this is how open discussions help improve projects like Shabad OS for the future!

Platform | Contact Us
----------| --------------
Slack | https://slack.shabados.com
WhatsApp | https://wa.me/15166196059

**Comment by HarminderSingh** [comment] 2019-02-11 21:15
20rG u must chek again, the other data from sikhitomax team is def better, check ur open issues, they have fix already. i got email from them, n they are very humble and have done the work. plz speak to dem as u can wrk 2gether g. 

why do alt pad chhed? panth is bigger than any scholar - i thnk ur approach is very much of haumai sorry to say

u think bcuz my english not very gud i need more explanation? very much ego you have

**Comment by HarminderSingh** [comment] 2019-02-11 21:26
y r u stopping d discussion @bhajneet 20r? dis is not a gursikh way.

**Comment by HarminderSingh** [comment] 2019-02-11 21:32
my email harminderkhalsa83@gmail.com - plz send invite - i talk openly

**Comment by Sarabveer** [comment] 2019-02-11 21:33
> why do alt pad chhed? panth is bigger than any scholar - i thnk ur approach is very much of haumai sorry to say

Agreed, default pad shed will be SGPC, but for Ekta, we will include Pad Sheds of many schools of though in the database for research

> i thnk ur approach is very much of haumai sorry to say

Waheguru, we are trying to be humble. If we have done anything wrong, then Bhul Chuk Muaaf.

**Comment by HarminderSingh** [comment] 2019-02-11 21:37
dat is not d ekta, dat is dufarh - split n more shanka

we talk more on d slack when u invite

**Comment by bhajneet** [comment] 2019-02-25 19:18
As a two week follow up to anyone reading publicly, Harminder joined the slack and was adamant on discussing a very specific topic which couldn't be resolved to their satisfaction.

The claim that Sttm db already has every single one of the changes proposed in the repo was very much untrue and corroborated by checking the Sttm site (which is supposed to be automatically updated with newest changes).

No email was forwarded to us. They joined with a Californian timezone (Slack uses the computer's timezone), but then claimed to be in Germany. Never provided any constructive criticism and instead used uncooperative/non-discussive language. Furthermore this email nor username is used anywhere else on the web.

We believe there is a small probability that this user is not a troll. Given all the above (and more), barring any further proof/verification given, it should be safe to assume that this was a rude attempt to harass a separate, independent, sikhi-based project.

**Comment by HarminderSingh** [comment] 2019-02-26 01:03
dis is only bcuz i ask how @bhajneet do 3000 change verification in 2 hour only. he is hurt bcuz it is clear dat he is blindly approve change to da gurbani

**Comment by bhajneet** [comment] 2019-02-26 02:21
As previously explained to you, those changes were not done to Gurbani. Some things might be too difficult for you to comprehend, but more likely you are trolling... If you are a fellow Sikh, please think hard about what you're trying to accomplish by engaging in such behavior and what might be a better approach.
