### ISSUE TITLE
TER6

### ISSUE THREAD

**Issue by UmeetSingh** [ShabadOS/database#664] opened 2019-03-12 01:41 UTC
> Use the preview tab to see the example given below. Edit the relevant information and preview the changes before submitting. You may delete these instructions.

| Key | Value |
| --- | --- |
| ID | TER6 |
| Source | Vaaran Bhai Gurdas Ji |
| Page | 28 |
| Line | gur isKI dw rUp dyiK; ieks bwJu n horsu dyKY [ |
| Correction | THIS ≠ THAT  |

PROOF (EDITION)

Image:
![Capture2](https://user-images.githubusercontent.com/47087634/54168727-64bcb900-4446-11e9-9017-0c883fa9edae.PNG)

**Comment by bhajneet** [comment] 2019-05-12 15:54
Duplicate of #598

**Closed by bhajneet** 2019-05-12 15:54 UTC
