### ISSUE TITLE
ASCII Gurmukhi  is incorrect for some records in database? 

### ISSUE THREAD

**Issue by onkarjit** [shabados/database#1876] opened 2022-07-01 13:42 UTC
### Describe the bug

When searching for the record with the id `KP7D`  in the `lines` table, and looking at the gurmukhi column for that record it says:
`gauVI kbIr jI pMcpdy₂ ]`

There is a subscript ₂ character in the ASCII Gurmukhi. 

```
const {
    toUnicode,
} = require( 'gurmukhi-utils' )

const asciiGurmukhi = 'gauVI kbIr jI pMcpdy₂ ]';
console.log(toUnicode( asciiGurmukhi ) );
```

When Gurmukhi Utils converts it to unicode, it parses the subscript ₂ literally.

It outputs:

`ਗਉੜੀ ਕਬੀਰ ਜੀ ਪੰਚਪਦੇ₂ ॥`

The subscript ₂ character shouldn't be there as we can see when we view the same [shabad line at SikhiToTheMax](https://www.sikhitothemax.org/shabad?id=1299&q=gkjp&type=1&source=all&highlight=14820).

I am using SQLite ShabadOS database,  to be specific [Release 4.8.0](https://github.com/shabados/database/releases/tag/4.8.0).

**Comment by bhajneet** [comment] 2022-07-01 14:35
In these instances, you may view the original sources. There are links available in our docs citations. As you'll see the original data contains these characters. 

https://docs.shabados.com/database/source-material

When trying to decide what is "right", the recommended course from us is to lookup the original sources and match them.

Closing this as working as intended. Please let us know if you have any other questions.

**Closed** 2022-07-01 14:35 UTC
Labels: ○ Type Bug
