### ISSUE TITLE
Add alternate pad chhed field to DB

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/database#376] opened 2019-02-18 15:22 UTC
SGPC saroops differ between themselves. For research purposes, it can help users to understand why there are differences in the displayed gurbani to what they may have found in their physical proofs.

In addition, work has been done by other schools of thought. One would imagine they are hoping to stir discussions on producing a singular, agreed-upon standard for the collective Sikh.

Since changes have been made to the SGPC saroops over time, it's easy to see that the standard can shift and is unlikely 100% "correct" today. Whatever "correct" means, is for a different discussion.

These alternates can help with verification, understanding nuances, and enriching a researcher with information.

Hopefully in the future, a larger collective group will begin the procedure to decide upon a single standard. We hope including this information helps them.

**Comment by Sarabveer** [comment] 2019-02-18 18:51
Duplicate of #95

**Closed by Sarabveer** 2019-02-18 18:51 UTC
